# Generated by Django 5.2.10 on 2026-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Portainer)', max_length=100)),
                ('description', models.TextField(help_text='Brief description of the service')),
                ('port', models.IntegerField(help_text='Port number (e.g., 9443)')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', help_text='Protocol (HTTP or HTTPS)', max_length=5)),
                ('icon_name', models.CharField(default='bi-globe', help_text="Bootstrap Icons class name (e.g., 'bi-server')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this service on the dashboard')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
    ]
