# Generated by Django 5.2.10 on 2026-02-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('services', 'Services'), ('projects', 'Projects'), ('tools', 'Tools'), ('other', 'Other')], default='services', help_text='Category for organizing services', max_length=50),
        ),
    ]
